process.env.NODE_ENV = "test";
process.env.PORT = process.env.PORT ?? "5000";
process.env.DB_HOST = process.env.DB_HOST ?? "localhost";
process.env.DB_PORT = process.env.DB_PORT ?? "5432";
process.env.DB_NAME = process.env.DB_NAME ?? "community_test";
process.env.DB_USER = process.env.DB_USER ?? "postgres";
process.env.DB_PASSWORD = process.env.DB_PASSWORD ?? "postgres";
process.env.JWT_SECRET = process.env.JWT_SECRET ?? "test-secret";
process.env.ADMIN_USER_IDS = process.env.ADMIN_USER_IDS ?? "1";
